engines:
  duplication:
    enabled: true
    config:
      languages:
        php:
          mass_threshold: 50
  fixme:
    enabled: true
  phpmd:
    enabled: true
    exclude_fingerprints:
    - 6f1741a30df682d3e9df65fac222b482  # allow js() method to be 2-character long
    - 8eca4c1426fc1508652d90a30744e7fd  # allow on() method to be 2-character long
    - 8eca4c1426fc1508652d90a30744e7fd  # allow $id property to be 2-character long
    - 5ea59add5ab787828057bd726957dc99  # allow $id property to be 2-character lond
    - 908ad3f93985ff14c44615cee6966c72  # View have a lot of public methods. Deal with it.
    checks:
      CleanCode/ElseExpression:
        enabled: false      # gives many incorrect suggestions
      Controversial/CamelCaseClassName:
        enabled: false      # because jQuery.php and similar class names
      Controversial/CamelCasePropertyName:
        enabled: false      # becasue we use _xx for private properties (that must remain public)
      Controversial/CamelCaseMethodName:
        enabled: false      # methods start with _xx for private methods (that must remain public)
      Design/WeightedMethodCount:
        enabled: false      # because we solve complex task, our classes may be complex
  radon:
    enabled: true
ratings:
  paths:
  - "src/**"
exclude_paths:
- "docs/**"
- "tests/**"
- "vendor/**"
