language: php

php:
    - '5.6'
    - '7.0'
    - '7.1'

services:
    - mysql

before_script:
    -  [[ ${TRAVIS_PHP_VERSION:0:3} == "7.0" ]] && php -S localhost:8888 &
    - composer install
    - mysql -e 'create database atk4;'
    - mysql atk4 < demos/atk4.sql
    - mv demos/db.travis.php demos/db.php
    - sudo $(which npm) install -g zombie

after_script:
    - echo $TRAVIS_BRANCH
    - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.0" ]]; then echo "Sending coverage report"; vendor/bin/test-reporter; fi
    - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.0" ]]; then echo "Sending codecov report"; bash <(curl -s https://codecov.io/bash); fi

script:
    - if [[ ${TRAVIS_PHP_VERSION:0:3} != "7.0" ]]; then NC="--no-coverage"; fi
    - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.0" ]]; then bash tools/test.sh; fi
      #- wget -O - http://localhost:8888/demos/button2.php 
    - ./vendor/phpunit/phpunit/phpunit $NC


cache:
  directories:
    - $HOME/.composer/cache

notifications:
    urls:
      - https://webhooks.gitter.im/e/b33a2db0c636f34bafa9

    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

    email: false
